name: cozydiary
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #影片播放
  video_player: ^2.2.17
  #API串接工具
  http:
  #firebase
  firebase_core: ^1.8.0
  firebase_database:
  google_sign_in: ^5.0.0
  firebase_auth: ^3.0.1
  #字體
  font_awesome_flutter: ^9.0.0
  flutter_staggered_grid_view: ^0.6.1
  masonry_grid: ^1.0.0
  #按鈕
  like_button: ^2.0.4
  readmore: ^2.1.0
  bottom_sheet: ^3.0.0
  image_picker: ^0.8.5
  #底部導覽套件
  curved_navigation_bar:
  spincircle_bottom_bar:
  page_transition: ^2.0.5
  #地圖套件
  google_maps_flutter: ^2.2.1
  custom_marker: ^1.0.0
  geolocator:
  geocoding:
  flutter_typeahead:
  flutter_google_places:

  flutter_map:
    ^3.0.0

    #個人位置

  flutter_map_location_marker:
    ^5.0.0+1

    #標記
  flutter_map_marker_cluster: ^1.0.0
  awesome_snackbar_content: ^0.0.8

  #狀態管理
  provider: ^6.0.0
  get: ^4.6.1
  #請求套件
  dio: ^4.0.6
  path_provider: ^2.0.10
  gallery_saver:
  liquid_progress_indicator: ^0.4.0
  #圖片選擇
  fluttertoast: ^8.0.9
  photo_manager: ^2.1.2
  #LocalDB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0
  #起始畫面
  flutter_native_splash: ^2.2.10
  #NetworkImage
  cached_network_image: ^3.2.2
  #選擇時間
  flutter_datetime_picker: ^1.5.1
  #可延展物件
  expandable: ^5.0.1
  #顏色組件
  flex_color_scheme: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #啟動畫面
flutter_native_splash:
  color: "#CAAF9A"
  image: "assets/images/Logo/logoWithouttBackground.png"

  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  #hive
  http:

# dependency_overrides:
#   firebase_messaging_platform_interface: ^3.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo/logoS.png"
  adaptive_icon_background: "assets/images/Logo/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/images/Logo/ic_launcher_adaptive_fore.png"
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/category/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
