// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbR8XPoOccxxFPl_D4ezStz4N1Ffujms',
    appId: '1:1084254307608:web:c09902d67c07dd9d57ca6d',
    messagingSenderId: '1084254307608',
    projectId: 'cozydiary-22111',
    authDomain: 'cozydiary-22111.firebaseapp.com',
    databaseURL: 'https://cozydiary-22111-default-rtdb.firebaseio.com',
    storageBucket: 'cozydiary-22111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSaM7T9vku1N2vVKJpjp0R6qh9YfVG1Wk',
    appId: '1:1084254307608:android:4dc1e76f7809be2a57ca6d',
    messagingSenderId: '1084254307608',
    projectId: 'cozydiary-22111',
    databaseURL: 'https://cozydiary-22111-default-rtdb.firebaseio.com',
    storageBucket: 'cozydiary-22111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2DdjS9bSFnGE1b05XlGwKcMz22aXbApw',
    appId: '1:1084254307608:ios:ef4a371e5e15601857ca6d',
    messagingSenderId: '1084254307608',
    projectId: 'cozydiary-22111',
    databaseURL: 'https://cozydiary-22111-default-rtdb.firebaseio.com',
    storageBucket: 'cozydiary-22111.appspot.com',
    androidClientId: '1084254307608-e3q1dtgtrshtn3184tsg3i3rn4v94s53.apps.googleusercontent.com',
    iosClientId: '1084254307608-98r0d65htt5dd2b0u7000hcb1khllgrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cozydiary',
  );
}
